services:
  events.database:
    image: postgres:latest
    container_name: events.database
    restart: unless-stopped
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./web_API/servers.json:/pgadmin4/servers.json
      - ./web_API/pgpass:/pgadmin4/pgpass
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown 5050:0 /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "